"""Central config for the SEP-1 uncertainty-aware RAG extension.

Swapping from the synthetic test fixtures to real MIMIC-IV-Note data (once
credentialed access is approved) should only require changing NOTES_PATH /
GROUND_TRUTH_PATH below (or the SEPSIS_NOTES_PATH / SEPSIS_GROUND_TRUTH_PATH
env vars) -- nothing in src/ should need to change.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

# --- Input data -------------------------------------------------------------
# Defaults point at the synthetic fixtures generated by data/generate_synthetic_data.py.
# Override with real MIMIC-IV-Note extracts (subject_id, hadm_id, text schema) via env vars.
NOTES_PATH = Path(
    os.environ.get("SEPSIS_NOTES_PATH", BASE_DIR / "data" / "synthetic" / "notes.jsonl")
)
GROUND_TRUTH_PATH = Path(
    os.environ.get(
        "SEPSIS_GROUND_TRUTH_PATH", BASE_DIR / "data" / "synthetic" / "ground_truth.csv"
    )
)

# --- Derived / build artifacts ----------------------------------------------
PROCESSED_DIR = BASE_DIR / "data" / "processed"
CHUNKS_PATH = PROCESSED_DIR / "chunks.jsonl"
EMBEDDINGS_PATH = PROCESSED_DIR / "embeddings.npy"
FAISS_INDEX_PATH = PROCESSED_DIR / "faiss_index" / "index.faiss"

OUTPUT_DIR = BASE_DIR / "output"
EVAL_DETAILED_PATH = OUTPUT_DIR / "eval_detailed.csv"
EVAL_SUMMARY_PATH = OUTPUT_DIR / "eval_summary.csv"

# --- Embedding backend --------------------------------------------------
# "sentence-transformers" is the only backend implemented today; kept as a named
# setting (rather than hardcoded) so a future swap (e.g. a clinical embedding model)
# is a one-line config change.
EMBEDDING_BACKEND = "sentence-transformers"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"  # same model MedGrounded's core pipeline uses

# --- Chunking -----------------------------------------------------------
CHUNK_SIZE = 500  # characters, matches MedGrounded's core pipeline
CHUNK_OVERLAP = 50  # characters

# --- Retrieval ------------------------------------------------------------
TOP_K = 5

# --- Generation -------------------------------------------------------------
LLM_MODEL = "claude-haiku-4-5"

# --- Uncertainty / self-consistency -----------------------------------------
SELF_CONSISTENCY_RUNS = 5
# Must be > 0: self-consistency needs sampling variance to be meaningful. At
# temperature=0 every run would be identical and agreement would trivially be 100%.
SELF_CONSISTENCY_TEMPERATURE = 0.7

# Weighted combination of the two confidence signals (must sum to 1.0).
RETRIEVAL_CONFIDENCE_WEIGHT = 0.5
SELF_CONSISTENCY_WEIGHT = 0.5

# Below this combined score, the final answer is force-overridden to
# "INSUFFICIENT EVIDENCE" regardless of what generation/self-consistency produced.
# This is the conformal-prediction-inspired "know when you don't know" gate.
LOW_CONFIDENCE_THRESHOLD = 0.6

# Bucket boundaries used by evaluate.py to report accuracy-by-confidence.
# (Low, Medium, High) as half-open [lo, hi) intervals over the combined score.
CONFIDENCE_BUCKETS = [
    ("Low", 0.0, 0.5),
    ("Medium", 0.5, 0.75),
    ("High", 0.75, 1.01),  # 1.01 so a perfect 1.0 score is inclusive
]

# --- SEP-1 sepsis bundle questions -------------------------------------------
# Five core SEP-1 (Severe Sepsis/Septic Shock Early Management Bundle) elements.
SEP1_QUESTIONS = [
    {
        "id": "q1_antibiotics_3h",
        "text": "Were broad-spectrum antibiotics administered within 3 hours of sepsis presentation?",
    },
    {
        "id": "q2_blood_culture_before_antibiotics",
        "text": "Were blood cultures drawn before antibiotics were administered?",
    },
    {
        "id": "q3_lactate_6h",
        "text": "Was an initial lactate level measured within 6 hours of sepsis presentation?",
    },
    {
        "id": "q4_lactate_repeat",
        "text": "If the initial lactate was elevated (>2 mmol/L), was a repeat lactate measured?",
    },
    {
        "id": "q5_fluid_30ml_kg",
        "text": "Was a 30 mL/kg crystalloid fluid bolus administered for septic shock or sepsis-induced hypotension?",
    },
]
